# Generated by Django 5.0 on 2024-01-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_photos_alter_photo_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photos',
        ),
    ]
