# Generated by Django 5.0 on 2024-01-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='todo.photo'),
        ),
    ]
