# Generated by Django 5.0 on 2024-01-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_remove_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='/default_images/murad.jpg', null=True, upload_to='task_photos/'),
        ),
    ]
